name: TerrificTotes CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:
            ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:
            ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:
            ${{ secrets.AWS_REGION }}
      - name: Run Tests
        run: make requirements && make dev-setup && make run-checks
  
  deploy-dev:
    name: Deploy Dev
    runs-on: ubuntu-latest
    # environment: development
    needs: run-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: 
            ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:
            ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:
            ${{ secrets.AWS_REGION }}
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        working-directory: terraform
        run: terraform init
      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve